FROM python:3.12-slim

# Instala dependências do sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    zip \
    unzip \
    openjdk-17-jdk \
    autoconf \
    automake \
    libtool \
    libffi-dev \
    cmake \
    libltdl-dev \
    libssl-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Instala buildozer e dependências Python
RUN pip install --upgrade pip && \
    pip install buildozer cython==0.29.36 virtualenv

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos do projeto
COPY . .

# Comando para compilar
CMD ["buildozer", "android", "debug"]
